/* images.js — mapping des icônes -> chemins */
(function () {
  window.IMG = {
    // ===== EXISTANT (exemples — garde/complète avec ton mapping actuel) =====
    goblet:			"images/goblet_squat.gif",
    dbbench:			"images/dumbbell_bench_press.gif",
    flydb:			"images/dumbbell_fly.gif",
    inclinedb:			"images/incline_dumbbell_press.gif",
    cabletri:			"images/cable_triceps_pushdown_close_grip.gif",
    lateral:			"images/lateral_raise.gif",
    rdl:			"images/romanian_deadlift_dumbbells.gif",
    onearmrow:			"images/one_arm_dumbbell_row.gif",
    landminerow:		"images/landmine_row.gif",
    dbcurl:			"images/dumbbell_biceps_curl.gif",
    hammer:			"images/hammer_curl.gif",
    sideplank:			"images/side_plank.gif",
    bulgarian:			"images/bulgarian_split_squat.gif",
    landminepress:		"images/landmine_press.gif",
    ohp:			"images/dumbbell_overhead_press.gif",
    reversefly:			"images/reverse_fly.gif",
    deadbug:			"images/dead_bug.gif",
    landminesquat:		"images/landmine_squat.gif",
    pushup:			"images/decline_push_up.gif",
    swing:			"images/kettlebell_swing.gif",
    farmer:			"images/farmer_walk.gif",
    plank:			"images/plank.gif",
    supersetA:			"images/curl_zottman.gif",
    supersetB:			"images/overhead_triceps_extension.gif",
    wu_breath_core:        	"images/wu_breath_core.gif",
    wu_hip_mobility:       	"images/wu_hip_mobility.gif",
    wu_band_abduction:     	"images/wu_band_abduction.gif",
    wu_band_pullapart:     	"images/wu_band_pullapart.gif",
    wu_shoulder_mob:       	"images/wu_shoulder_mobility.gif",
    wu_hip_hinge:          	"images/wu_hip_hinge.gif",
    wu_glute_bridge:       	"images/wu_glute_bridge.gif",
    wu_band_row:           	"images/wu_band_row.gif",
    wu_cardio_lowimpact:   	"images/wu_low_impact_cardio.gif",
    wu_tspine_open:        	"images/wu_tspine_open.gif",
    wu_glute_bridge_iso:   	"images/wu_glute_bridge_iso.gif",
    wu_facepull:           	"images/wu_facepull_band.gif",
    wu_wrist_shoulder:     	"images/wu_wrist_shoulder.gif",
    wu_external_rotation:  	"images/wu_external_rotation_band.gif",
    wu_glute_kickback:     	"images/wu_glute_kickback_band.gif",
    wu_dead_bug_light:     	"images/wu_dead_bug_light.gif",
    wu_shoulder:		"images/warmup_shoulder_mobility.png",
    wu_bandpull:		"images/warmup_band_pull_aparts.gif",
    wu_squat:			"images/warmup_bodyweight_squat.gif",
    wu_pushup:			"images/warmup_pushup.gif",
    wu_hinge:			"images/warmup_hip_hinge.gif",
    wu_rowband:			"images/warmup_band_row.gif",
    wu_external:		"images/warmup_external_rotation.gif",
    wu_lunge:			"images/warmup_dynamic_lunge.gif",
    wu_jj:			"images/warmup_jumping_jacks.gif",

    hip_thrust_db:          	"images/hip_thrust_dumbbell.gif",
    onearm_row_db:          	"images/one_arm_dumbbell_row.gif",
    landmine_press:         	"images/landmine_press.gif",
    dead_bug:               	"images/dead_bug.gif",
    cable_tri_close:        	"images/cable_triceps_pushdown_close_grip.gif",
    rdl_db:                 	"images/romanian_deadlift_dumbbells.gif",
    db_ohp_seated:          	"images/seated_dumbbell_overhead_press.gif",
    band_abduction_standing:	"images/band_abduction_standing.gif",
    pallof_press_band:      	"images/pallof_press_band.gif",
    hammer_curl:            	"images/hammer_curl.gif",
    band_row_seated:        	"images/band_row_seated.gif",
    glute_bridge_db:        	"images/glute_bridge_dumbbell.gif",
    lateral_raise:          	"images/lateral_raise.gif",
    side_plank:             	"images/side_plank.gif",
    farmer_hold:            	"images/farmer_hold.gif",
    incline_pushup_bench:   	"images/incline_pushup_bench.gif",
    chest_supported_row:    	"images/chest_supported_row_dumbbell.gif",
    hip_thrust_pause:       	"images/hip_thrust_pause.gif",
    superset_arms:          	"images/superset_arms.gif",
    hollow_hold:            	"images/hollow_hold.gif",
    facepull_band:          	"images/facepull_band.gif"
  };
})();
